"""Check maintained documentation; optionally regenerate branding with pinned PRESS."""

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
GUIDES = (
    'docs/README.md', 'docs/user-guide/installation.md', 'docs/user-guide/project-setup.md',
    'docs/user-guide/tasks-and-recovery.md', 'docs/reference/commands.md', 'docs/reference/evidence.md',
    'docs/development/architecture.md', 'docs/development/testing.md',
    'docs/development/automation.md', 'docs/development/documentation.md',
)
BRANDED = ('README.md', 'CONTRIBUTING.md', 'prd/README.md', 'design/README.md', *GUIDES)
PROVENANCE = ('package.json', 'brand/tokens.json', 'lib/tokens.mjs', 'lib/emit.mjs', 'lib/region.mjs')
REGION = re.compile(r'^<!-- >>> press:masthead v([^ ]+) sha256:([0-9a-f]{12}) GENERATED by @natjswenson/press, do not edit -->\n(.*?)\n<!-- <<< press:masthead -->$', re.M | re.S)
LINK = re.compile(r'\[[^\]]*\]\(([^\s)]+)\)')


def digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def prose(text: str) -> str:
    """Exclude fenced examples, including outer fences with shorter inner fences."""
    result, fence = [], None
    for line in text.splitlines():
        match = re.match(r'^\s{0,3}(`{3,}|~{3,})(.*)$', line)
        if fence:
            if match and match[1][0] == fence[0] and len(match[1]) >= len(fence) and not match[2].strip():
                fence = None
            continue
        if match:
            fence = match[1]
            continue
        result.append(line)
    return '\n'.join(result)


def anchors(text: str) -> set[str]:
    seen, result = {}, set()
    for line in prose(text).splitlines():
        match = re.match(r'^#{1,6}\s+(.+?)\s*#*$', line)
        if not match:
            continue
        title = re.sub(r'<[^>]*>', '', match[1]).lower()
        title = re.sub(r'[^\w\- ]', '', title).replace(' ', '-')
        count = seen.get(title, 0)
        seen[title] = count + 1
        result.add(f'{title}-{count}' if count else title)
    return result


def check_links(root: Path, names: tuple[str, ...]) -> None:
    for name in names:
        path = root / name
        for link in LINK.findall(prose(path.read_text(encoding='utf-8'))):
            url = urlsplit(link)
            if url.scheme or url.netloc:
                continue
            target = (path.parent / unquote(url.path)).resolve() if url.path else path
            if not target.is_relative_to(root.resolve()) or not target.exists():
                raise ValueError(f'{name}: broken local link {link}')
            if url.fragment and target.is_file() and target.suffix == '.md':
                if unquote(url.fragment) not in anchors(target.read_text(encoding='utf-8')):
                    raise ValueError(f'{name}: missing heading {link}')


def check_brand(root: Path) -> None:
    receipt = json.loads((root / 'docs/branding.json').read_text())
    if receipt['schema'] != 1 or set(receipt['regions']) != set(BRANDED):
        raise ValueError('Brand receipt must cover every maintained branded document')
    if set(receipt['source_sha256']) != set(PROVENANCE) or any(
        not re.fullmatch(r'[0-9a-f]{64}', value) for value in receipt['source_sha256'].values()
    ):
        raise ValueError('Brand provenance hashes are incomplete')
    for name in BRANDED:
        text = (root / name).read_text()
        matches = list(REGION.finditer(text))
        if len(matches) != 1 or text.count('<!-- >>> press:masthead') != 1 or text.count('<!-- <<< press:masthead') != 1:
            raise ValueError(f'{name}: missing, duplicate or malformed PRESS region')
        found = matches[0]
        body_hash = digest(found[3].replace('\r\n', '\n').rstrip().encode())[:12]
        if found[1] != receipt['press_version'] or found[2] != body_hash or found[0] != receipt['regions'][name]:
            raise ValueError(f'{name}: PRESS region drift from adopted pin')
        if prose(text).find('\n# ') >= 0 or not text.startswith('# '):
            raise ValueError(f'{name}: expected one document title')


def check(root: Path = ROOT) -> None:
    for name in BRANDED:
        if not (root / name).is_file() or (root / name).is_symlink():
            raise ValueError(f'Missing regular maintained document: {name}')
    check_links(root, (*BRANDED, 'prd/0009-plugin-structure.md', 'design/0009-plugin-structure.md',
                       'skills/software-factory/SKILL.md', 'skills/software-factory/protocol.md'))
    index = (root / 'docs/README.md').read_text()
    for name in GUIDES[1:]:
        relative = str(Path(name).relative_to('docs'))
        if f']({relative})' not in index:
            raise ValueError(f'Documentation index lacks navigation to {name}')
    if '](docs/README.md)' not in (root / 'README.md').read_text():
        raise ValueError('Root README lacks documentation navigation')
    check_brand(root)


def sync_brand(press_root: Path, root: Path = ROOT) -> None:
    """Run the existing PRESS CLI using an isolated consumer registry, never edit PRESS."""
    receipt_path = root / 'docs/branding.json'
    version = json.loads(receipt_path.read_text())['press_version']
    installed = json.loads((press_root / 'package.json').read_text())['version']
    if installed != version:
        raise ValueError(f'Expected PRESS {version}, found {installed}; review a pin change first')
    sources = {name: digest((press_root / name).read_bytes()) for name in PROVENANCE}
    targets = []
    for number, name in enumerate(BRANDED):
        title = (root / name).read_text().splitlines()[0]
        targets.append({'id': f'factory-{number}', 'repo': 'software-factory', 'path': name,
                        'region': 'masthead', 'syntax': 'md', 'emitter': 'readme-masthead',
                        'params': {'document_kind': 'Codex + Claude Code plugin' if name == 'README.md' else title[2:]},
                        'init': {'insertAfter': '^' + re.escape(title) + '$'}})
    with tempfile.TemporaryDirectory(prefix='factory-press-') as temporary:
        copy = Path(temporary) / 'press'
        shutil.copytree(press_root, copy, ignore=shutil.ignore_patterns('node_modules', '.git'))
        (copy / 'targets.json').write_text(json.dumps({'targets': targets}))
        for target in targets:
            command = ['node', str(copy / 'bin/press.js'), 'emit', '--repo', str(root), '--target', target['id']]
            if '<!-- >>> press:masthead' not in (root / target['path']).read_text():
                command.append('--init')
            subprocess.run(command, check=True)
        subprocess.run(['node', str(copy / 'bin/press.js'), 'check', '--repo', str(root)], check=True)
        subprocess.run(['node', str(copy / 'bin/press.js'), 'lint', *(str(root / p) for p in BRANDED)], check=True)
    regions = {}
    for name in BRANDED:
        found = REGION.search((root / name).read_text())
        if not found:
            raise ValueError(f'PRESS did not generate {name}')
        regions[name] = found[0]
    receipt_path.write_text(json.dumps({'schema': 1, 'press_version': version,
        'source': 'https://github.com/natejswenson/claude-skills/tree/main/skills/press/skills/press',
        'source_sha256': sources, 'regions': regions}, indent=2) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sync-brand', action='store_true')
    parser.add_argument('--press-root', type=Path)
    args = parser.parse_args()
    if args.sync_brand:
        if not args.press_root:
            parser.error('--sync-brand requires --press-root to the matching installed PRESS package')
        sync_brand(args.press_root.resolve())
    elif args.press_root:
        parser.error('--press-root requires --sync-brand')
    check()
    print('Maintained documentation links, navigation and pinned PRESS regions match.')
